name: CI - Build & Test .NET 8 & Deploy

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout do cÃ³digo
        uses: actions/checkout@v3

      - name: ğŸ§° Instalar .NET 8 Preview
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: ğŸ” Restaurar pacotes
        run: dotnet restore Users.sln

      - name: ğŸ› ï¸ Build do projeto
        run: dotnet build Users.sln --configuration Release --no-restore

      - name: ğŸ§ª Executar testes (Release)
        run: |
          dotnet test Users.sln \
            --configuration Release \
            --no-restore \
            --no-build \
            --verbosity normal

  push-to-acr:
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout do cÃ³digo
        uses: actions/checkout@v3

      - name: ğŸ”‘ Login no Azure Container Registry
        run: |
          echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: ğŸ³ Build da imagem Docker
        run: docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/users-api:{{ github.sha }} .

      - name: ğŸš€ Push da imagem para o ACR
        run: docker push ${{ secrets.ACR_LOGIN_SERVER }}/users-api:{{ github.sha }}

  push-to-aks:
    needs: push-to-acr
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
      - name: ğŸ“¥ Checkout do cÃ³digo
        uses: actions/checkout@v3
        
      - name: ğŸ”‘ Login no Azure Kubernetes 
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          
      - name: ğŸ” Validar conexÃ£o com o cluster
        run: kubectl get nodes
      
      - name: ğŸ” Aplicar secrets
        run: |
          kubectl create secret generic secret-users \
          -n users \
          --from-literal=Jwt__Key="${{ secrets.JWT_KEY }}" \
          --from-literal=Jwt__Issuer="${{ secrets.JWT_ISSUER }}" \
          --from-literal=ConnectionStrings__DbConnection="${{ secrets.DB_CONNECTION }}" \
          --dry-run=client -o yaml | kubectl apply -f -
      
      - name: ğŸš€ Deploy no AKS
        run: |
          kubectl apply -f k8s/prod/svc-users.yml
          kubectl apply -f k8s/prod/deployment-users.yml
          kubectl set image deployment/deployment-users \
            fiapcloudgames-users=${{ secrets.ACR_LOGIN_SERVER }}/users-api:{{ github.sha }} \
            -n users
          kubectl apply -f k8s/prod/hpa-users.yml

      - name: â±ï¸ Aguardar rollout
        run: kubectl rollout status deployment/deployment-users -n users
